CREATE TABLE CUSTOMER (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100)
);

CREATE TABLE PRODUCT (
     ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
     DESCRIPTION VARCHAR(130),
     PRICE NUMERIC(20, 2)
);

CREATE TABLE ORDERS (
     ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
     CUSTOMER_ID INTEGER REFERENCES CUSTOMER(ID),
     ORDERS_DATE TIMESTAMP,
     TOTAL NUMERIC(20, 2)
);

CREATE TABLE ORDERS_ITEM (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ORDERS_ID INTEGER REFERENCES ORDERS(ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT(ID),
    QUANTITY INTEGER
);